---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: all-helm-application
spec:
  generators:
    - matrix:
        generators:
          - git:
              repoURL: 'https://github.com/Fredichou/argocd-test.git'
              revision: HEAD
              files:
                - path: 'all-applications/deployments_helm/*.json'
          - clusters:
              selector:
                matchLabels:
                  argocd.argoproj.io/secret-type: cluster
  template:
    metadata:
      name: hello-kubernetes 
    spec:
      project: default
      source:
        repoURL: 'https://github.com/Fredichou/argocd-test.git'
        path: '{{application.path}}'
        targetRevision: HEAD
        helm:
          valueFiles:
          - values.yaml
          - '{{application.helmFile}}'  
      destination:
        server: https://kubernetes.default.svc
        namespace: argo
