---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: all-helm-application
spec:
  generators:
  - git:
      repoURL: 'https://github.com/Fredichou/argocd-test.git'
      revision: HEAD
      files:
      - path: 'all-applications/deployments_helm/*.json'
  template:
    metadata:
      name: hello-kubernetes 
    spec:
      project: default
      source:
        repoURL: 'https://github.com/Fredichou/argocd-test.git'
        path: '{{application.path}}'
        targetRevision: HEAD
        helm:
          parameters:
          - name: message
            value: Kikoo
          valueFiles:
          - '{{application.helmFile}}'  
      destination:
        server: https://kubernetes.default.svc
        namespace: argo
